### ISSUE TITLE
Small typo in Wiki Chapter 2

### ISSUE THREAD

**Issue by alpepi** [Timmeey86/fs22-script-modding-tutorial#1]
There's a small typo in Chapter 2, section "Overwriting functions rather than appending to them". I don't think I can do a PR for the wiki myself.
> The `Utils` class provided by GIANTS <ins>**alos**</ins> allows overwriting

I really like this wiki you wrote! I'm glad I stumbled on it. I'm hopeful I'll finally be able to understand modding for FS! :)

**Comment by Timmeey86** [comment]
Thanks for the report and I'm glad it is useful :-)
I fixed the typo
